### ISSUE TITLE
WiFi stops working after short amount of time

### ISSUE THREAD

**Issue by sowiecki** [Nase00/Stranger-Lights#1]
Possibly a memory leak.

**Comment by Nase00** [comment]
Might need to lift WiFiClient from displayMessage.

**Comment by sowiecki** [comment]
Seems to be [this](https://github.com/esp8266/Arduino/issues/4497); `Serial.print(ESP.getFreeHeap());` reports smaller and smaller heap size each loop.

**Comment by sowiecki** [comment]
Resolved by moving `jsonBuffer` into `loop()`.
